### ISSUE TITLE
Brew indicates 7.3.1 is available but no update on brew

### ISSUE THREAD

**Issue by arendjantetteroo** [drewdeponte/git-ps-rs#303]
I've installed git patch stack through the installation instructions at https://book.git-ps.sh/tool/installation on an Ubuntu 24.04 release. 

At the end of commands it shows:
```  
A new release of gps is available!

  7.3.1 - https://github.com/drewdeponte/git-ps-rs/releases/tag/7.3.1
```

Does brew have seperate packages for linux and is 7.3.1 available on mac os, or should there be a new brew release for both?

**Comment by drewdeponte** [comment]
Sorry for the confusion. We switched brew taps a while back and the book didn't get updated until the other day. 

You can solve the problem by doing the following.

brew uninstall git-ps-rs
brew untap uptech/oss
brew tap drewdeponte/oss
brew install git-ps-rs
